# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:25
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.ProductAttribute')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('_order',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='exturl',
            field=models.URLField(blank=True, null=True, verbose_name='External link'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku2',
            field=cartridge.shop.fields.SKUField(blank=True, max_length=20, null=True, verbose_name='Additional SKU'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.Product'),
        ),
    ]
