# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160427_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exturl',
            field=models.URLField(blank=True, null=True, verbose_name='External link'),
        ),
    ]
